# Generated by Django 4.0.3 on 2024-02-09 16:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0003_alter_salesperson_employee_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='date_of_sale',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
