# Generated by Django 4.0.3 on 2024-02-09 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0004_sale_date_of_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='date_of_sale',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
